name: persistencia_datos_local
description: Sistema de Persistencia de Datos Local
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.9.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  mailer: ^6.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icono/tech.gif
    - assets/icono/tech.png

# ICONO SOLO ANDROID
flutter_icons:
  android: true
  ios: false
  image_path: "assets/icono/tech.png"

# SPLASH SOLO ANDROID
flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#000000"
  image: assets/icono/tech.png

  android_12:
    image: assets/icono/tech.png
    icon_background_color: "#000000"
